applications:
  microservices-java:
    message: Configured by Azure Spring Cloud - Java
  microservices-dotnet:
    message: Configured by Azure Spring Cloud - DotNet
  city-microservice-dotnet:
    azure:
      cosmosdb:
        uri: https://azure-spring-cloud-taller-cosmosdb.documents.azure.com:443/
        key: 0DOjkFtvGEccDtzVk8JR4xy6tHPbiWt898onKMoDXUUTOmWh9kcnzneTw79tNZjAEBUxrNSnJj8ei5Lbn2qbWg==
        database: taller-cosmosdb
  weather-microservice-dotnet:
    connectionstrings:
      taller-mysqldb: Server=taller-mysqlserver.mysql.database.azure.com; Port=3306; Database=taller-mysqldb; Uid=tallermysqluser@taller-mysqlserver; Pwd=Password1234; SslMode=Preferred;
